#!/usr/bin/env python3
"""Visa Radar generator. Pulls the latest Passport Index data (MIT), writes ./public. Run: pip install pycountry && python3 build.py"""
import csv,glob,json,os,re,shutil,datetime,html,hashlib,urllib.request,pycountry
SITE=(os.environ.get("SITE_URL") or "https://visaradar.com").rstrip("/"); OUT="public"; TODAY=datetime.date.today()
RAW="https://raw.githubusercontent.com/imorte/passport-index-data/main/"; e=html.escape
ADS=os.environ.get("ADSENSE_ID","").strip(); MAIL=os.environ.get("CONTACT_EMAIL") or "contact@visaradar.com"
V=lambda f:hashlib.md5(open(f"src/{f}","rb").read()).hexdigest()[:8]
ADSLOT=os.environ.get("ADSENSE_SLOT","").strip(); NOADS={"privacy/","terms/","disclaimer/","contact/","404.html"}
AM=f'<meta name="google-adsense-account" content="{ADS}">' if ADS else ""
def AD(): return f'<p class="adl">Advertisement</p><ins class="adsbygoogle" style="display:block;min-height:120px" data-ad-client="{ADS}" data-ad-slot="{ADSLOT}" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({{}});</script>' if ADS and ADSLOT else ""
TH='<script>document.documentElement.classList.add("js");try{document.documentElement.dataset.theme=localStorage.getItem("vr:theme")||"light"}catch(e){}</script>'
RADAR='<svg class="radar" viewBox="0 0 400 400" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1.2"><circle cx="200" cy="200" r="60"/><circle cx="200" cy="200" r="110"/><circle cx="200" cy="200" r="160"/><circle cx="200" cy="200" r="196"/><path d="M200 4V396M4 200H396"/><g class="sweep"><path d="M200 200L200 6" stroke-width="2.5"/><path d="M200 200L200 6A194 194 0 0 1 300 32Z" fill="currentColor" fill-opacity=".18" stroke="none"/></g></g></svg>'
MARK='<svg viewBox="0 0 40 40" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="20" cy="20" r="17"/><circle cx="20" cy="20" r="9"/><path d="M20 20L33 9"/></svg>'
def fetch(n):
    try: return urllib.request.urlopen(RAW+n,timeout=30).read().decode()
    except Exception as x: print("offline, using cached",n); return None
t=fetch("passport-index-tidy-iso2.csv"); rd=fetch("README.md")
m=re.search(r"Last updated: \*\*(.+?)\*\*",rd or ""); os.makedirs("data/snapshots",exist_ok=True)
OLDU=open("data/updated.txt").read().strip()
if t and m and m[1]!=OLDU:
    try: shutil.copy("data/passport-index-tidy-iso2.csv","data/snapshots/"+datetime.datetime.strptime(OLDU,"%d %B %Y").date().isoformat()+".csv")
    except Exception as x: print("snapshot not archived",x)
if t: open("data/passport-index-tidy-iso2.csv","w").write(t)
else: t=open("data/passport-index-tidy-iso2.csv").read()
if m: open("data/updated.txt","w").write(m[1])
UPD=open("data/updated.txt").read().strip()
try: AGE=(TODAY-datetime.datetime.strptime(UPD,"%d %B %Y").date()).days
except: AGE=None
FIX=dict(US="United States",GB="United Kingdom",RU="Russia",KR="South Korea",KP="North Korea",IR="Iran",SY="Syria",VN="Vietnam",TR="Turkey",CZ="Czechia",BO="Bolivia",TZ="Tanzania",VE="Venezuela",MD="Moldova",LA="Laos",BN="Brunei",PS="Palestine",TW="Taiwan",XK="Kosovo",CD="DR Congo",CG="Congo",FM="Micronesia",VA="Vatican City",MK="North Macedonia",CV="Cape Verde",SZ="Eswatini",HK="Hong Kong",MO="Macao")
def nm(c):
    if c in FIX: return FIX[c]
    x=pycountry.countries.get(alpha_2=c); return (getattr(x,"common_name",None) or x.name) if x else c
SH={"visa free":"vf","visa on arrival":"voa","eta":"eta","e-visa":"ev","visa required":"vr","no admission":"na"}
R={}
for r in csv.DictReader(t.splitlines()):
    if r["Requirement"]=="-1": continue
    R.setdefault(r["Passport"],{})[r["Destination"]]=r["Requirement"] if r["Requirement"].isdigit() else SH.get(r["Requirement"],"vr")
K=["vf","voa","eta","ev","vr","na"]
kind=lambda v:"vf" if v.isdigit() else v
INFO={"vf":("Visa-free","No visa is needed for a tourist stay. Carry a valid passport, onward travel and proof of funds.",["Check passport validity; many countries want six months beyond your stay.","Book onward or return travel.","Carry accommodation details and proof of funds."]),
"voa":("Visa on arrival","The visa is issued at the border.",["Check passport validity and blank pages.","Carry the fee in cash and by card, plus photos.","Keep your return ticket and hotel booking to hand."]),
"eta":("Electronic authorisation","Apply online before you fly. Airlines check it at check-in.",["Apply only on the official government site; lookalike sites charge extra.","Apply well before departure and keep the approval.","Travel on the same passport you applied with."]),
"ev":("e-Visa","Apply online for an electronic visa before you travel.",["Use the official e-visa portal only.","Upload a passport scan, photo and itinerary.","Print the approval and carry it with you."]),
"vr":("Visa required","Apply through the embassy, consulate or official portal before you travel.",["Find the embassy or official application route.","Gather passport, photos, bank statements, itinerary and insurance.","Book biometrics early and apply before buying non-refundable tickets."]),
"na":("Entry not permitted","Entry is currently not permitted for this passport.",["Check your government's travel advice and the destination's official site."])}
lab=lambda v:INFO[kind(v)][0]+(f" · {v} days" if v.isdigit() else "")
N={c:nm(c) for c in set(R)|{d for v in R.values() for d in v}}
CNT={p:{k:sum(1 for v in d.values() if kind(v)==k) for k in K} for p,d in R.items()}
score=lambda p:CNT[p]["vf"]+CNT[p]["voa"]+CNT[p]["eta"]
RANK=sorted(R,key=lambda p:(-score(p),N[p])); POS={p:i+1 for i,p in enumerate(RANK)}
import xml.etree.ElementTree as ET, email.utils
def load_news():
    try: items={i["u"]+"|"+i["t"]:i for i in json.load(open("data/news.json"))}
    except Exception: items={}
    try: feeds=json.load(open("data/feeds.json"))
    except Exception: feeds=[]
    KW=re.compile(r"visa|passport|etias|\bees\b|\besta\b|\beta\b|schengen|immigration|border|e-visa|evisa|travel authori",re.I)
    for f in feeds:
        try: root=ET.fromstring(urllib.request.urlopen(urllib.request.Request(f["url"],headers={"User-Agent":"VisaRadarBot/1.0"}),timeout=8).read())
        except Exception as x: print("feed skipped:",f["name"],type(x).__name__); continue
        for it in root.iter():
            if it.tag.split("}")[-1] not in ("item","entry"): continue
            g=lambda n:next((c for c in it if c.tag.split("}")[-1]==n),None)
            t,l,dt=g("title"),g("link"),g("pubDate") or g("published") or g("updated")
            if t is None or l is None or dt is None or not (t.text or "").strip(): continue
            u=(l.get("href") or l.text or "").strip()
            if not u.startswith("http"): continue
            try: d=email.utils.parsedate_to_datetime(dt.text).date()
            except Exception:
                try: d=datetime.date.fromisoformat(dt.text.strip()[:10])
                except Exception: continue
            sm=g("description") or g("summary"); x=re.sub(r"\s+"," ",html.unescape(re.sub(r"<[^>]+>"," ",(sm.text or "") if sm is not None else ""))).strip()
            x=x[:137]+"..." if len(x)>140 else x; ti=t.text.strip()
            if f.get("filter") and not KW.search(ti+" "+x): continue
            items[u+"|"+ti]={"t":ti,"u":u,"s":f["name"],"d":d.isoformat(),"x":x}
    cut=(TODAY-datetime.timedelta(days=120)).isoformat()
    out=sorted([i for i in items.values() if i["d"]>=cut],key=lambda i:i["d"],reverse=True)[:80]
    json.dump(out,open("data/news.json","w"),indent=1,ensure_ascii=False); return out
NEWS=load_news()
TAGRX=[("Europe",r"schengen|etias|\bees\b|\beu\b|europe"),("UK",r"\buk\b|united kingdom|britain|home office|gov\.uk"),("USA",r"\bus\b|u\.s\.|united states|\besta\b|uscis|state department"),("e-Visa and eTA",r"e-?visa|\beta\b|etias|\besta\b|authori[sz]ation"),("Asia-Pacific",r"asia|australia|japan|china|india|thailand|vietnam|singapore|turkmenistan|korea|zealand|indonesia"),("Africa and Middle East",r"africa|uganda|kenya|egypt|uae|emirates|saudi|qatar|morocco")]
ntags=lambda i:[n for n,r in TAGRX if re.search(r,(i["t"]+" "+i["x"]).lower())]
fmtd=lambda s:datetime.date.fromisoformat(s).strftime("%d %b %Y")
def nitem(i): return f"<article class='nws' data-tags='{'|'.join(ntags(i))}'><h3><a href='{e(i['u'])}' rel='noopener nofollow' target='_blank'>{e(i['t'])}</a></h3><p class='mute'>{e(i['s'])} · {fmtd(i['d'])}</p>"+(f"<p>{e(i['x'])}</p>" if i["x"] else "")+"</article>"
def nsec(d):
    nms=[N[d]]+{"GB":["UK"],"US":["US","U.S."],"AE":["UAE"],"KR":["Korea"],"CZ":["Czech Republic"]}.get(d,[]); rx=r"(?<!\w)(?:"+"|".join(map(re.escape,nms))+r")(?!\w)"
    m=[i for i in NEWS if re.search(rx,i["t"])][:4]
    return f"<section><h2>Latest news</h2>{''.join(nitem(i) for i in m)}<p><a href='/news/'>All visa news</a></p></section>" if m else ""
def NH(): return f"<section><h2>Latest visa news</h2>{''.join(nitem(i) for i in NEWS[:5])}<p><a href='/news/'>More news</a></p></section>" if NEWS else ""
EASE={"vf":0,"voa":1,"eta":2,"ev":3,"vr":4,"na":5}
def snap():
    fs=sorted(glob.glob("data/snapshots/*.csv"))
    if not fs: return None,{}
    o={}
    for r in csv.DictReader(open(fs[-1])):
        if r["Requirement"]!="-1": o.setdefault(r["Passport"],{})[r["Destination"]]=r["Requirement"] if r["Requirement"].isdigit() else SH.get(r["Requirement"],"vr")
    return os.path.basename(fs[-1])[:-4],o
OLDD,OLD=snap(); OLDP=datetime.date.fromisoformat(OLDD).strftime("%d %B %Y") if OLDD else ""
def dirn(o,v):
    a,b=EASE[kind(o)],EASE[kind(v)]; return 1 if b<a or (a==b and int(v)>int(o)) else -1
CH=[(p,d,OLD[p][d],v) for p in R for d,v in R[p].items() if p in OLD and d in OLD[p] and OLD[p][d]!=v and not (kind(v)==kind(OLD[p][d])=="vf" and not(v.isdigit() and OLD[p][d].isdigit()))]
CHP={};CHD2={};CHX={}
for r in CH: CHP.setdefault(r[0],[]).append(r); CHD2.setdefault(r[1],[]).append(r); CHX[(r[0],r[1])]=r
def crow(p,d,o,v,f):
    up=dirn(o,v)>0; return f'<a class="row" href="/{"country" if f=="p" else "passport"}/{(d if f=="p" else p).lower()}/"><span>{e(N[d if f=="p" else p])}</span><span class="mute">{lab(o)} → {lab(v)}</span><span class="{"up" if up else "down"}">{"Easier" if up else "Harder"}</span></a>'
def csec(rows,f):
    if not rows or not OLDD: return ""
    rows=sorted(rows,key=lambda r:(-dirn(r[2],r[3]),N[r[1] if f=="p" else r[0]]))
    return f'<section><h2>Changes since {OLDP} <span class="mute">{len(rows)}</span></h2><div class="ledger">{"".join(crow(*r,f) for r in rows[:80])}</div>'+(f'<p class="mute">Showing 80 of {len(rows)}.</p>' if len(rows)>80 else "")+f'<p class="note">Compared with the dataset snapshot dated {OLDP}. Differences can include data corrections as well as policy changes.</p></section>'
def chnote(p,d):
    r=CHX.get((p,d)); return f'<p class="note">Changed since {OLDP}: was <b>{lab(r[2])}</b>, now <b>{lab(r[3])}</b>.</p>' if r else ""
PP="AE SA QA KW IN PK EG PH GB US DE FR CA AU NG ZA".split()
DD="AE US GB FR DE IT ES TR TH JP SG MY ID IN CN KR EG SA QA AU CA NZ GR PT NL CH AT MV LK VN MA ZA BR MX".split()
CORR={(p,d) for p in PP for d in DD if p!=d and p in R and d in R[p]}
sl=lambda p,d:f"visa/{p.lower()}-to-{d.lower()}/"
PAGES=[]
def page(path,title,desc,body,ld="",noidx=False):
    url=f"{SITE}/{path}"
    if not noidx: PAGES.append(url)
    p=f"{OUT}/{path}index.html"; os.makedirs(os.path.dirname(p),exist_ok=True)
    age=f" ({AGE} days before this build)" if AGE is not None else ""
    ads=f'<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={ADS}" crossorigin="anonymous"></script>' if ADS and not noidx and path not in NOADS else ""
    open(p,"w").write(f'<!DOCTYPE html><html lang="en" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:type" content="website">{TH}<meta name="theme-color" content="#0f3d2e">{AM}<link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/icon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Hanken+Grotesk:wght@400;500;600&display=swap"><link rel="stylesheet" href="/assets/style.css?v={V("style.css")}">{ld}{ads}</head><body><header><a class="mark" href="/">{MARK}Visa Radar</a><nav><a href="/passport/">Passports</a><a href="/country/">Destinations</a><a href="/rank/">Rank</a><a href="/tools/">Tools</a><a href="/changes/">Changes</a><a href="/eu/">EU entry</a><a href="/news/">News</a><a href="/guides/">Guides</a><button id="theme" type="button" aria-label="Switch between light and dark mode">&#9680;</button></nav></header><main>{body}</main><footer><p class="flinks"><a href="/guides/">Guides</a><a href="/faq/">FAQ</a><a href="/glossary/">Glossary</a><a href="/editorial-policy/">Editorial policy</a><a href="/about/">About</a><a href="/disclaimer/">Disclaimer</a><a href="/terms/">Terms of use</a><a href="/privacy/">Privacy policy</a><a href="/contact/">Contact</a><button type="button" id="adc" class="lnk" hidden>Ad and cookie settings</button></p><p>Visa Radar is an independent information service. It is not a government agency, embassy or visa service, and nothing here is legal or immigration advice. Always confirm entry rules with the official government source before you travel.</p><p>Visa data: Passport Index snapshot dated {UPD}{age}, MIT licence. Live details: REST Countries, Open-Meteo and <a href="https://www.exchangerate-api.com">Rates By Exchange Rate API</a>.</p><p>&copy; {TODAY.year} Visa Radar</p></footer><script type="speculationrules">{{"prefetch":[{{"where":{{"href_matches":"/*"}},"eagerness":"moderate"}}]}}</script><script src="/assets/app.js?v={V("app.js")}" defer></script></body></html>')
def stamp(v): k=kind(v); return f'<div class="stamp k-{k}"><b>{INFO[k][0]}</b>'+(f"<span>{v} days</span>" if v.isdigit() else "")+"</div>"
def chip(p,d): v=R[p][d]; return f'<a class="chip" href="/{sl(p,d) if (p,d) in CORR else "country/"+d.lower()+"/"}">{e(N[d])}'+(f"<i>{v}d</i>" if v.isdigit() else "")+"</a>"
LIVE=lambda c:f'<section class="live" id="live" data-cc="{c}"><h2>Right now in {e(N[c])}</h2><div id="facts" class="ledger"><p class="mute">Loading live details…</p></div></section>'
def index_page(path,title,items,url):
    page(path,title+" | Visa Radar",title,f"<h1>{title}</h1><div class='chips big'>"+"".join(f'<a class="chip" href="/{url}{c.lower()}/">{e(N[c])}</a>' for c in sorted(items,key=lambda c:N[c]))+"</div>")
def features():
    json.dump({c.numeric:c.alpha_2 for c in pycountry.countries},open(f"{OUT}/data/iso.json","w"))
    open(f"{OUT}/icon.svg","w").write('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="9" fill="#0f3d2e"/><g fill="none" stroke="#c3a15b" stroke-width="2"><circle cx="20" cy="20" r="13"/><circle cx="20" cy="20" r="6"/><path d="M20 20L31 9"/></g></svg>')
    json.dump({"name":"Visa Radar","short_name":"Visa Radar","start_url":"/","display":"standalone","background_color":"#fbf8f1","theme_color":"#0f3d2e","icons":[{"src":"/icon.svg","sizes":"any","type":"image/svg+xml","purpose":"any"}]},open(f"{OUT}/manifest.webmanifest","w"))
    rk={p:1+sum(1 for q in R if score(q)>score(p)) for p in R}
    tr=lambda ps:"".join(f"<tr><td>{rk[p]}</td><td><a href='/passport/{p.lower()}/'>{e(N[p])}</a></td><td>{score(p)}</td><td>{CNT[p]['vf']}</td><td>{CNT[p]['voa']}</td><td>{CNT[p]['eta']}</td><td>{CNT[p]['ev']}</td><td>{CNT[p]['vr']+CNT[p]['na']}</td></tr>" for p in ps)
    th="".join(f"<th>{h}</th>" for h in ("Rank","Passport","Score","Visa-free","On arrival","eTA","e-Visa","Visa needed"))
    page("rank/","Global Passport Rank | Visa Radar","All passports ranked by travel freedom score.",f"<h1>Global passport rank</h1><p class='lede'>All {len(R)} passports ranked by how many destinations they reach visa-free, on arrival or with an electronic authorisation. Ties share a rank. Click a heading to sort.</p><p class='note'>Scores are calculated by Visa Radar from the dataset dated {UPD} and can differ from other sites.</p><input id='flt' class='fld' type='search' placeholder='Filter passports' aria-label='Filter passports'><div class='tw'><table class='tbl' id='rk'><thead><tr>{th}</tr></thead><tbody>{tr(RANK)}</tbody></table></div>")
    INB={d:[R[p][d] for p in R if d in R[p]] for d in N}; opn=lambda d:sum(1 for v in INB[d] if kind(v) in ("vf","voa","eta"))
    WL=sorted(N,key=lambda d:(-opn(d),N[d])); wr={d:1+sum(1 for x in N if opn(x)>opn(d)) for d in N}
    wrow="".join(f"<tr><td>{wr[d]}</td><td><a href='/country/{d.lower()}/'>{e(N[d])}</a></td><td>{opn(d)}</td><td>{sum(1 for v in INB[d] if kind(v)=='ev')}</td><td>{sum(1 for v in INB[d] if kind(v) in ('vr','na'))}</td></tr>" for d in WL)
    page("rank/welcoming/","Most Welcoming Destinations | Visa Radar","Destinations ranked by how many passports can enter without a prior visa.",f"<h1>Welcoming destinations</h1><p class='lede'>Destinations ranked by the number of passports that can enter visa-free, on arrival or with an electronic authorisation.</p><input id='flt' class='fld' type='search' placeholder='Filter destinations' aria-label='Filter destinations'><div class='tw'><table class='tbl' id='rk'><thead><tr><th>Rank</th><th>Destination</th><th>Open to</th><th>e-Visa</th><th>Visa needed</th></tr></thead><tbody>{wrow}</tbody></table></div>")
    sl4=lambda m,n:"".join(f"<label>{'Passport' if m=='p' else 'Destination'} {i+1}<select data-i='{i}'></select></label>" for i in range(n))
    page("compare/","Compare Passports | Visa Radar","Compare up to four passports side by side.",f"<h1>Compare passports</h1><p class='lede'>Choose two to four passports to compare scores and see where their rules differ.</p><form class='cmp' data-cmp='p' onsubmit='return false'>{sl4('p',4)}</form><div id='out' class='tw'></div>")
    page("compare/destinations/","Compare Destinations | Visa Radar","Compare entry openness of up to four destinations.",f"<h1>Compare destinations</h1><p class='lede'>See how open each destination is, and what your own passport needs for each.</p><form class='cmp' data-cmp='d' onsubmit='return false'>{sl4('d',4)}<label>Your passport<select id='me'></select></label></form><div id='out' class='tw'></div>")
    def bars(it):
        mx=max(v for _,v in it) or 1
        return f'<svg class="chart" viewBox="0 0 640 {len(it)*28+8}" role="img" aria-label="Bar chart">'+"".join(f'<text class="bt" x="0" y="{i*28+18}">{e(l)}</text><rect class="bb" x="190" y="{i*28+4}" width="{v/mx*380:.0f}" height="18" rx="2"/><text class="bt" x="{190+v/mx*380+8:.0f}" y="{i*28+18}">{v}</text>' for i,(l,v) in enumerate(it))+"</svg>"
    tot={k:sum(CNT[p][k] for p in R) for k in K}; T=sum(tot.values()); x=0; seg=""
    for k in K: w=tot[k]/T*620; seg+=f'<rect class="m-{k}" x="{x:.1f}" y="0" width="{w:.1f}" height="34"/>'; x+=w
    leg="".join(f'<span><i class="m-{k}" style="background:currentColor"></i>{INFO[k][0]}: {tot[k]:,} ({tot[k]/T:.0%})</span>' for k in K)
    page("charts/","Passport Charts | Visa Radar","Charts of passport power, welcoming destinations and the global mix of visa rules.",f"<h1>Charts</h1><h2>Strongest passports</h2>{bars([(N[p],score(p)) for p in RANK[:15]])}<h2>Most welcoming destinations</h2>{bars([(N[d],opn(d)) for d in WL[:15]])}<h2>Global mix of entry rules</h2><svg class='chart' viewBox='0 0 620 34' role='img' aria-label='Share of entry requirement types'>{seg}</svg><div class='legend'>{leg}</div><p class='mute'>Across {T:,} passport-to-destination pairs in the dataset dated {UPD}.</p>")
    lg="".join(f'<span><svg width="14" height="14"><rect width="14" height="14" class="m-{k}"/></svg> {t}</span>' for k,t in (("vf","Visa-free"),("voa","On arrival"),("eta","eTA"),("ev","e-Visa"),("vr","Visa required"),("self","Your passport")))
    page("map/","Visa Map | Visa Radar","Interactive world map of visa requirements for any passport.",f"<h1>Visa map</h1><p class='lede'>Choose a passport to colour the world by entry rule. Hover or tap a country for details.</p><label>Passport<select id='mp' class='fld'></select></label><div id='map' role='img' aria-label='World map coloured by visa requirement'><noscript>Turn on JavaScript to see the map, or use the passport pages.</noscript></div><div class='legend'>{lg}</div>",ld='<script defer src="https://cdn.jsdelivr.net/npm/d3@7.9.0/dist/d3.min.js"></script><script defer src="https://cdn.jsdelivr.net/npm/topojson-client@3.1.0/dist/topojson-client.min.js"></script>')
def changes():
    if not OLDD:
        page("changes/","Visa Rule Changes | Visa Radar","Changes in visa rules between dataset snapshots.","<h1>What changed</h1><p class='lede'>No earlier snapshot is stored yet. Comparisons appear after the next data update.</p>"); return
    ez=sum(1 for r in CH if dirn(r[2],r[3])>0); hd=len(CH)-ez
    osc={p:sum(1 for v in OLD[p].values() if kind(v) in ("vf","voa","eta")) for p in OLD if p in R}; nsc={p:score(p) for p in osc}
    ork={p:1+sum(1 for q in osc if osc[q]>osc[p]) for p in osc}; nrk={p:1+sum(1 for q in nsc if nsc[q]>nsc[p]) for p in osc}
    rows="".join(f"<tr><td>{nrk[p]}</td><td><a href='/passport/{p.lower()}/'>{e(N[p])}</a></td><td>{ork[p]}</td><td>{osc[p]}</td><td>{nsc[p]}</td><td class='{'up' if nsc[p]>osc[p] else 'down' if nsc[p]<osc[p] else ''}'>{nsc[p]-osc[p]:+d}</td><td>{len(CHP.get(p,[]))}</td></tr>" for p in sorted(osc,key=lambda p:(-(nsc[p]-osc[p]),N[p])))
    op=lambda D,d:sum(1 for p in D if d in D[p] and kind(D[p][d]) in ("vf","voa","eta"))
    dl={d:op(R,d)-op(OLD,d) for d in N}; led=lambda ds,c:"".join(f"<a class='row' href='/country/{d.lower()}/'><span>{e(N[d])}</span><span class='{c}'>{dl[d]:+d} passports</span></a>" for d in ds)
    top=sorted(N,key=lambda d:(-dl[d],N[d]))[:10]; low=sorted(N,key=lambda d:(dl[d],N[d]))[:10]
    page("changes/","What Changed in Visa Rules | Visa Radar",f"{len(CH):,} visa rule differences between the {OLDP} and {UPD} snapshots.",f"<h1>What changed</h1><p class='lede'>Between the dataset snapshots dated {OLDP} and {UPD}, {len(CH):,} passport-to-destination rules differ: {ez:,} became easier and {hd:,} became harder.</p><p class='note'>This compares two community dataset snapshots. Differences include data corrections as well as policy changes, so confirm any rule on the official source.</p><h2>Destinations that opened up most</h2><div class='ledger'>{led(top,'up')}</div><h2>Destinations that tightened most</h2><div class='ledger'>{led(low,'down')}</div><h2>Passports: score and rank change</h2><p class='mute'>Score is the number of destinations reachable visa-free, on arrival or with an electronic authorisation. Click a heading to sort.</p><input id='flt' class='fld' type='search' placeholder='Filter passports' aria-label='Filter passports'><div class='tw'><table class='tbl' id='rk'><thead><tr><th>Rank now</th><th>Passport</th><th>Rank then</th><th>Score then</th><th>Score now</th><th>Change</th><th>Rules changed</th></tr></thead><tbody>{rows}</tbody></table></div>")
def eu():
    rv=TODAY.strftime("%d %B %Y"); FREE=set("AT BE BG HR CY CZ DK EE FI FR DE GR HU IE IT LV LT LU MT NL PL PT RO SK SI ES SE IS LI NO CH".split())
    aff=sorted([p for p in R if p not in FREE and "DE" in R[p] and kind(R[p]["DE"])=="vf"],key=lambda p:N[p])
    rev=f"<p class='note'>Status reviewed {rv} from public reporting. Rules and dates change, so check the official portals: <a href='https://travel-europe.europa.eu/ees'>EES</a> and <a href='https://travel-europe.europa.eu/etias'>ETIAS</a>.</p>"
    page("eu/","EU Entry: EES, ETIAS and the 90/180 Rule | Visa Radar","Current status of the EU Entry/Exit System and ETIAS, who is affected, and a 90/180-day calculator.",f"<h1>Entering the EU and Schengen</h1><p class='lede'>What is live, what is coming, and how to stay within the 90/180-day rule.</p>{rev}<div class='ledger'><a class='row' href='/eu/ees/'><span>Entry/Exit System (EES)</span><span class='up'>In operation since 10 April 2026</span></a><a class='row' href='/eu/etias/'><span>ETIAS travel authorisation</span><span class='down'>Not open. No confirmed start date</span></a><a class='row' href='/eu/calculator/'><span>90/180-day calculator</span><span class='mute'>Plan your stay</span></a></div><h2>Who this affects</h2><p>In our dataset, {len(aff)} passports can enter Germany visa-free and are outside EU, EEA and Swiss free movement. These travellers are covered by the 90/180 rule, EES and, once it opens, ETIAS.</p><div class='chips'>{''.join(f'<a class=chip href=/passport/{p.lower()}/>{e(N[p])}</a>' for p in aff)}</div><h2>Beware of lookalike sites</h2><p>ETIAS applications cannot be made yet. Any site selling an ETIAS application today is not legitimate. Only use the official EU portal when it opens.</p>")
    page("eu/ees/","Entry/Exit System (EES) Explained | Visa Radar","What the EU Entry/Exit System is and what to expect at the border.",f"<h1>Entry/Exit System (EES)</h1><p class='lede'>EES replaces passport stamping with a digital record of entries, exits and refusals for short-stay non-EU visitors.</p>{rev}<h2>What to expect</h2><ul><li>It applies to non-EU travellers on a short stay of up to 90 days in any 180 days.</li><li>On your first crossing you give a facial image and fingerprints. Later crossings are faster.</li><li>It is free. There is nothing to apply for in advance.</li><li>Reported rollout: progressive from 12 October 2025, fully operational at all external borders from 10 April 2026. One immigration-law update reports that temporary flexibility measures ended on 6 September 2026.</li></ul><p>EES counts your days automatically, so use the <a href='/eu/calculator/'>90/180 calculator</a> to plan.</p><p><a href='/eu/'>Back to EU entry</a></p>")
    page("eu/etias/","ETIAS Explained: Status, Fee, Who Needs It | Visa Radar","Status of the EU ETIAS travel authorisation, the planned fee and who must apply.",f"<h1>ETIAS travel authorisation</h1><p class='lede'>ETIAS will be an online authorisation for visa-exempt travellers to Schengen countries. It is not open yet.</p>{rev}<h2>Status</h2><p>Earlier EU communication pointed to the last quarter of 2026. Newer reporting says the official portal dropped that window and a launch in 2027 looks likely, with no confirmed date. We will update this page when the EU announces one.</p><h2>Key facts reported so far</h2><ul><li>Fee: EUR 20, valid for three years, after an increase from the original EUR 7.</li><li>Travellers under 18 and over 70 are reported to be exempt from the fee but still need to register.</li><li>Applications are made on the official EU site only. Anyone selling ETIAS applications now is not legitimate.</li></ul><p><a href='/eu/'>Back to EU entry</a> · <a href='/eu/calculator/'>90/180 calculator</a></p>")
    page("eu/calculator/","Schengen 90/180-Day Calculator | Visa Radar","Calculate how many days you have used and left in the Schengen 90/180-day rule.","<h1>90/180-day calculator</h1><p class='lede'>Add your past Schengen trips to see days used, days left and how long you can stay if you enter on a given date.</p><div id='sc' class='calc'><div id='trips'></div><button type='button' id='addT' class='btn'>Add a trip</button><p><label>Check date<br><input type='date' id='ref'></label></p><div id='res' class='result' aria-live='polite'></div></div><p class='note'>Planning guide only. Your border record in EES is what officers use. Not legal advice.</p><noscript><p>Turn on JavaScript to use the calculator.</p></noscript>")
def tools():
    page("trip/","Multi-Country Trip Visa Checker | Visa Radar","Check entry rules for every stop on your route with one passport.","<h1>Trip checker</h1><p class='lede'>Add the countries on your route in order. We show the entry rule for each stop and what to arrange before you fly. The page address saves your trip, so you can bookmark or share it.</p><div id='trip'><label>Your passport<select id='tp' class='fld'></select></label><div id='stops'></div><p><button type='button' id='addS' class='btn'>Add a destination</button> <button type='button' id='shr' class='btn'>Copy link to this trip</button></p><div id='tout' aria-live='polite'></div></div><p class='note'>Transit and layover rules are not covered by this data, so check them with your airline. Confirm every rule on the official government site.</p><noscript><p>Turn on JavaScript to use the trip checker.</p></noscript>")
    page("dual/","Dual Passport Planner: Which Passport to Use | Visa Radar","See which of your passports gives the easiest entry to each destination.","<h1>Dual passport planner</h1><p class='lede'>Hold two or three passports? See which one gives the easiest entry to each destination, and how many places they reach together.</p><div id='dual' class='cmp'><label>Passport 1<select></select></label><label>Passport 2<select></select></label><label>Passport 3<select></select></label></div><div id='dout' aria-live='polite'></div><p class='note'>Many countries require you to enter and leave on the passport matching your nationality there, and some treat dual nationals as citizens only. Airlines also check that your passport matches your booking. Confirm the rules for each country before you choose.</p><noscript><p>Turn on JavaScript to use the planner.</p></noscript>")
    T=[("/trip/","Trip checker","Entry rules for every stop on a route"),("/dual/","Dual passport planner","Which passport to use where"),("/compare/","Compare passports","Up to four side by side"),("/compare/destinations/","Compare destinations","Openness and your own rule"),("/map/","Visa map","Any passport, coloured by rule"),("/eu/calculator/","90/180-day calculator","Plan Schengen stays"),("/rank/welcoming/","Welcoming destinations","Most open countries"),("/charts/","Charts","Rankings and the global mix"),("/passport-validity/","Passport validity checker","3-month and 6-month rules")]
    page("tools/","Visa and Passport Tools | Visa Radar","All Visa Radar tools in one place.","<h1>Tools</h1><div class='ledger'>"+"".join(f"<a class='row' href='{u}'><span>{t}</span><span class='mute'>{d}</span></a>" for u,t,d in T)+"</div>")
SCHENGEN="AT BE BG HR CZ DK EE FI FR DE GR HU IS IT LV LI LT LU MT NL NO PL PT RO SK SI ES SE CH".split()
OFF={"US":[("U.S. Department of State: visas","https://travel.state.gov/content/travel/en/us-visas.html"),("ESTA (official application)","https://esta.cbp.dhs.gov/")],
"GB":[("Check if you need a UK visa","https://www.gov.uk/check-uk-visa"),("UK Electronic Travel Authorisation","https://www.gov.uk/eta")],
"CA":[("Canada eTA","https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html")],
"AU":[("Australia Home Affairs: visa finder","https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-finder")],
"NZ":[("Immigration New Zealand","https://www.immigration.govt.nz/")],"JP":[("Ministry of Foreign Affairs of Japan: visas","https://www.mofa.go.jp/j_info/visit/visa/index.html")],
"SG":[("Immigration and Checkpoints Authority","https://www.ica.gov.sg/")],"TH":[("Thailand e-Visa","https://www.thaievisa.go.th/")],
"TR":[("Turkey e-Visa","https://www.evisa.gov.tr/")],"IN":[("India e-Visa","https://indianvisaonline.gov.in/evisa/")],
"AE":[("UAE Federal Authority for Identity and Citizenship","https://icp.gov.ae/")],"SA":[("Saudi visa portal","https://visa.visitsaudi.com/")],
"EG":[("Egypt e-Visa","https://visa2egypt.gov.eg/")],"KR":[("Korea K-ETA","https://www.k-eta.go.kr/")],"VN":[("Vietnam e-Visa","https://evisa.gov.vn/")],
"ID":[("Indonesia e-Visa","https://evisa.imigrasi.go.id/")],"LK":[("Sri Lanka ETA","https://eta.gov.lk/")],"KE":[("Kenya eTA","https://www.etakenya.go.ke/")],
"MA":[("Morocco e-Visa","https://www.acces-maroc.ma/")],"ZA":[("South Africa Department of Home Affairs","https://www.dha.gov.za/")],"MY":[("Malaysia Immigration Department","https://www.imi.gov.my/")],
"PH":[("Philippines Bureau of Immigration","https://immigration.gov.ph/")]}
for _c in SCHENGEN: OFF.setdefault(_c,[]).append(("EU entry information: EES and ETIAS","https://travel-europe.europa.eu/"))
def srcs(d):
    li="".join(f"<li><a href='{u}' rel='noopener' target='_blank'>{e(t)}</a> <span class='mute'>official</span></li>" for t,u in OFF.get(d,[]))
    nm_=N[d]; wiki=f"https://en.wikipedia.org/wiki/Special:Search?search={urllib.parse.quote('Visa policy of '+nm_)}"
    miss="" if d in OFF else f"<p class='mute'>We have not added a verified official portal for {e(nm_)} yet. Look for the government immigration or foreign ministry website, and avoid lookalike sites.</p>"
    return f"<section><h2>Official sources</h2><ul>{li}<li><a href='https://www.iatatravelcentre.com/' rel='noopener' target='_blank'>IATA Travel Centre</a> <span class='mute'>airline reference</span></li><li><a href='{wiki}' rel='noopener' target='_blank'>Visa policy of {e(nm_)} on Wikipedia</a> <span class='mute'>reference with citations</span></li></ul>{miss}<p class='mute'>Check your <a href='/passport-validity/'>passport validity</a> too. Apply only through official portals.</p></section>"
def report(p,d): return f"<p class='mute'>See an error? <a href='mailto:{MAIL}?subject={urllib.parse.quote('Correction: '+N[p]+' to '+N[d])}'>Report it</a> with a link to the official source.</p>"
def validity():
    json.dump(sorted({u for v in OFF.values() for _,u in v}),open("data/official_links.json","w"),indent=1)
    page("passport-validity/","Passport Validity Checker: 3-Month and 6-Month Rules | Visa Radar","Check whether your passport meets a destination's validity rule, including the Schengen 3-month and 10-year rules.","<h1>Passport validity checker</h1><p class='lede'>Airlines can refuse boarding if your passport is too close to expiry. Pick the rule your destination states, enter your dates, and check.</p><div class='calc' id='pv'><div class='cmp'><label>Passport expiry date<input type='date' id='pe'></label><label>Passport issue date <span class='mute'>(Schengen check)</span><input type='date' id='pi'></label><label>Entry date<input type='date' id='pen'></label><label>Exit date<input type='date' id='pex'></label><label>Rule to check<select id='pr'><option value='stay'>Valid for the whole stay</option><option value='in3'>3 months after entry</option><option value='in6'>6 months after entry</option><option value='out3'>3 months after departure</option><option value='out6'>6 months after departure</option><option value='sch'>Schengen: 3 months after departure, issued within 10 years</option></select></label></div><div id='pres' class='result' aria-live='polite'></div></div><h2>The common rules</h2><ul><li><strong>Six-month rule:</strong> some countries want at least six months of validity, counted from your arrival or your departure. The destination decides which.</li><li><strong>Three-month rule:</strong> the Schengen Area requires validity of at least three months after you plan to leave, and the passport must have been issued within the previous 10 years.</li><li><strong>Length of stay:</strong> some countries only need the passport to be valid for the whole stay.</li><li><strong>Blank pages:</strong> some countries also require one or two blank pages.</li></ul><p class='note'>Rules differ by country and change. We do not publish a country-by-country list because we could not verify one from an authoritative source. Find your destination's rule on its official site (linked on each destination page), then pick it above.</p><noscript><p>Turn on JavaScript to use the checker.</p></noscript>")
P=lambda x:f"<p>{x}</p>"
UL=lambda *i:"<ul>"+"".join(f"<li>{x}</li>" for x in i)+"</ul>"
def GUIDES():
    tot={k:sum(CNT[p][k] for p in R) for k in K}; T=sum(tot.values()); pc=lambda k:f"{tot[k]/T:.0%}"; top=", ".join(f"{N[p]} ({score(p)})" for p in RANK[:3])
    return [
("visa-types","Visa-free, visa on arrival, eTA, e-visa: what each means","The five kinds of entry rule you will see on Visa Radar, and how to prepare for each.",[
("Visa-free",P("You can enter without applying in advance, usually for a set number of days. You still need a valid passport, and officers can ask for proof of onward travel, accommodation and funds.")),
("Visa on arrival",P("The visa is issued at the border or airport. Expect a fee and a queue. Some countries issue it only at certain entry points, and your airline may ask about it at check-in.")),
("eTA or electronic authorisation",P("A short online check, linked to your passport, that you complete before you fly. It is not a visa, but airlines will not board you without it. Examples include the US ESTA, the Canada eTA and the UK ETA. Use only the official site.")),
("e-Visa",P("A full visa that you apply for online and receive before travel. It usually asks for more documents and takes longer than an eTA.")),
("Embassy visa",P("You apply at an embassy, consulate or approved centre, often with an appointment and biometrics. Allow weeks rather than days, and apply before buying non-refundable tickets.")),
("How common is each?",P(f"Across the {T:,} passport-to-destination pairs in our dataset dated {UPD}: {pc('vf')} are visa-free, {pc('voa')} are visa on arrival, {pc('eta')} need an eTA, {pc('ev')} need an e-visa and {pc('vr')} need a visa in advance."))]),
("visa-scams","How to avoid visa and eTA scams","Lookalike sites charge extra for free or low-cost official services. Here is how to spot them.",[
("Check the address",P("Official immigration sites normally sit on a government domain. Be wary of sites that rank high in search ads but use a generic .com, .org or .info address.")),
("Know what is free",P("Some official systems cost little or nothing, and imitators add large service fees for the same form. Compare the price with the official portal linked on each Visa Radar destination page.")),
("Systems that are not open yet",P("Some schemes have been announced but cannot be applied for. Any site selling an application for a scheme that has not launched, such as ETIAS at the time of writing, should be treated as a scam. See our <a href='/eu/etias/'>ETIAS page</a>.")),
("Protect your documents",UL("Do not send a passport scan to a site you have not verified.","Pay only on a secure page and keep the receipt.","If you paid a fake site, contact your bank or card issuer straight away and report it to your local consumer authority."))]),
("schengen-90-180-rule","The Schengen 90/180-day rule explained","How the rolling 180-day window works and how to stay within it.",[
("The rule",P("Visa-exempt visitors may stay in the Schengen Area for up to 90 days in any 180-day period. The 180 days is a rolling window that looks back from each day, not a calendar half-year.")),
("One area, one limit",P("Days in all Schengen countries are added together. Countries outside Schengen, such as the UK, do not count. Check the current member list before you plan.")),
("Counting days",UL("Both the day you enter and the day you leave count.","Short trips add up. Two 45-day visits within 180 days use the whole allowance.","Since the Entry/Exit System, border systems record your days automatically.")),
("Plan with a tool",P("Use our <a href='/eu/calculator/'>90/180-day calculator</a> to see days used and how long you can stay from a chosen date. Read about <a href='/eu/ees/'>EES</a> too."))]),
("how-to-apply-for-a-visa","How to apply for a visa: a step-by-step checklist","A practical order of work for first-time applicants.",[
("1. Confirm you need one",P("Check your passport and destination on Visa Radar, then confirm on the official government site, which is always the final word.")),
("2. Check passport validity",P("Make sure your passport meets the destination's validity rule and has blank pages. Use the <a href='/passport-validity/'>validity checker</a>.")),
("3. Gather documents",UL("Passport and recent photos in the required format.","Proof of funds, such as bank statements.","Itinerary, accommodation and return or onward tickets.","Travel insurance, where required, and an invitation letter if applicable.")),
("4. Apply on the official channel",P("Use the official portal or the embassy's approved centre. Fill in every field accurately, because mismatches cause refusals.")),
("5. Allow time and track it",P("Processing times vary widely and change. Apply early, keep your reference number and do not book non-refundable travel until you are approved."))]),
("visa-refused","What to do if your visa is refused","Stay calm, read the reason and plan the next step.",[
("Read the refusal letter",P("It usually states the reason and whether you can appeal or ask for a review. Rules differ by country.")),
("Do not hide a refusal",P("Many applications ask whether you have been refused before. Answer truthfully, because a false answer can cause a long ban.")),
("Fix the cause",UL("Missing or weak documents: gather stronger evidence.","Unclear purpose or itinerary: explain it clearly.","Insufficient funds or ties to home: show real, verifiable evidence.")),
("Reapply or appeal",P("Where an appeal exists, follow the deadline in the letter. Otherwise reapply once the issue is fixed. For complex cases, consider an authorised immigration adviser, not a random online agent."))]),
("overstay-consequences","What happens if you overstay a visa-free stay","Why a few extra days can have long-term effects.",[
("Why it matters",P("Visa-free and visa-on-arrival stays have a hard end date. Exceeding it can lead to fines, detention, removal and entry bans, depending on the country.")),
("Effects on future travel",P("An overstay can be recorded in border systems and can lead to refusals or extra questions on later visa applications, in the same country and sometimes elsewhere.")),
("If you are close to the limit",UL("Check whether an extension is available and apply before the deadline.","Keep proof of any delay outside your control, such as a cancelled flight.","Contact the local immigration authority early."))]),
("transit-visas","Do you need a visa to change planes?","Airside and landside transit, and what to check before booking a connection.",[
("Airside transit",P("You stay inside the international area and never pass border control. Many nationalities need no visa for this, but some do, for specific airports.")),
("Landside transit",P("You enter the country, for example to collect bags on separate tickets or switch airports. This often needs the same entry permission as a visit.")),
("What to check",UL("Whether your tickets are on one booking, so bags are checked through.","The transit rules for your passport at each connecting country.","Your airline's guidance, since they can refuse boarding.")),
("Our data",P("Visa Radar's dataset covers entry rules, not transit rules. Always confirm transit on the official site or with your airline."))]),
("how-passport-rankings-work","How passport rankings work and why sites disagree","What a travel freedom score measures, and the limits of any ranking.",[
("The score",P(f"On Visa Radar, a passport's score is the number of destinations it reaches visa-free, on arrival or with an electronic authorisation. At our {UPD} snapshot the leaders were {top}. See the full <a href='/rank/'>global rank</a>.")),
("Why numbers differ",P("Rankings depend on the data source, the date and what counts as access. Some indexes use airline data and some use community-maintained data. Some count e-visas and others do not. Two honest rankings can therefore differ.")),
("What a ranking cannot tell you",P("A score says nothing about how easy a visa is to get, how long you can stay or whether rules for your trip changed last week. Check the <a href='/changes/'>changes tracker</a> and the official source before you travel."))]),
("before-you-fly-checklist","Before you fly: an international travel checklist","Twelve things to check in the week before departure.",[
("Documents",UL("Passport valid for the destination's rule, with blank pages.","Visa, eTA or e-visa approval, saved offline and printed.","Return or onward ticket, accommodation details and proof of funds.")),
("Health and insurance",UL("Travel insurance that covers medical care and cancellation.","Any vaccine certificate the destination requires, such as yellow fever for some routes.","Prescription medicines in original packaging, with a doctor's letter if needed.")),
("Practical",UL("Arrival or customs declarations that must be completed online.","Phone roaming or an eSIM, plus a payment card that works abroad.","Copies of key documents stored separately from the originals.","Emergency contacts and your embassy's details.")),
("Last check",P("Re-open the official source for your destination within a few days of departure, because rules can change at short notice."))]),
("purposes-of-visit","Tourist, business, work, study or transit: which category fits?","Why the purpose of your trip decides the permission you need.",[
("Tourism and visiting family",P("Short leisure trips and visits to family or friends usually fall under visitor or tourist rules. Paid work is not allowed.")),
("Business visits",P("Meetings, conferences and contract talks are often allowed on a visitor permission, but selling directly to the public or doing paid work usually is not. The wording of the rules differs, so check what counts as business activity.")),
("Work and study",P("Employment and courses of study almost always need a specific visa, even where visitors are visa-free. Entering as a tourist and then working or studying can lead to refusal, removal and entry bans.")),
("Transit",P("Passing through a country on the way to a third destination has its own rules. Read our <a href='/guides/transit-visas/'>transit guide</a>."))]),
("passport-renewal-checklist","Passport renewal checklist: when and how to renew","Renew early enough that validity rules never catch you out.",[
("When to renew",P("Many destinations ask for three or six months of remaining validity, so a passport that looks fine can fail the rule. Test your dates with our <a href='/passport-validity/'>validity checker</a> and renew well before you book.")),
("What you will usually need",UL("Your current passport and the application form from your issuing authority.","Photos that meet the official specification.","The fee and any identity or citizenship documents the authority requires.")),
("Timing",P("Issuing authorities publish processing times and they change with demand. Apply early and avoid buying non-refundable travel until the new passport is in your hands.")),
("After you receive it",P("Check every detail and sign it if required. Authorisations linked to your old passport number, such as an eTA, normally have to be applied for again."))]),
("travel-insurance-and-visas","Travel insurance and visas: what to know","When insurance is required and what to look for in a policy.",[
("Where it is required",P("Some visa types and destinations ask for proof of insurance, and applicants for a Schengen visa must show medical cover that meets the minimum rules. Check the requirement for your category.")),
("Even where it is optional",P("Medical treatment, evacuation and repatriation abroad can be very expensive. Insurance is worth having for almost any international trip.")),
("What to look for",UL("Medical cover with emergency evacuation and repatriation.","Trip cancellation and baggage cover.","Clear terms on pre-existing conditions and activities such as hiking or driving.")),
("Keep proof handy",P("Carry the policy certificate on paper and on your phone, ideally with an English version."))]),
("digital-arrival-cards","Digital arrival cards and online entry forms","Many countries now want a form completed online before you land.",[
("What they are",P("Some countries ask visitors to submit arrival, health or customs details online, sometimes within a set number of days before travel. They are separate from visas and eTAs.")),
("How to handle them",UL("Find the form on the destination's official government site only.","Enter your passport details exactly as printed.","Save the confirmation or QR code offline in case airport Wi-Fi fails.")),
("Beware of fake sites",P("Lookalike sites charge for forms that are free or cheap. Read our <a href='/guides/visa-scams/'>scam guide</a>, and check the news page for recent launches."))]),
("dual-citizenship-travel","Travelling with two passports: the basics","How to use dual nationality sensibly when you travel.",[
("Use the right passport at the border",P("Many countries expect their own citizens to enter and leave on their own passport, and some treat dual nationals as citizens only. Check the rules for each country you will pass through.")),
("Keep your documents consistent",P("The passport you give the airline should match your booking and any visa or eTA. Switching passports mid-trip can cause check-in problems.")),
("Compare your options",P("Our <a href='/dual/'>dual passport planner</a> shows which of your passports gives the easiest entry to each destination."))]),
("short-vs-long-stay-visas","Short-stay vs long-stay visas","The difference matters for what you may do and how long you may stay.",[
("Short stay",P("Covers tourism, family visits and short business trips, usually for a few months at most. Schengen short-stay visas are known as type C.")),
("Long stay",P("Covers work, study and family reunion beyond the short-stay limit. Many countries issue a national long-stay visa and then a residence permit after arrival. Schengen long-stay visas are type D.")),
("Why it matters",P("A short-stay permission generally cannot be turned into a work or study permit while you are in the country. Apply for the category that matches your real plan."))]),
("visa-extensions","Can you extend your stay? What to know about visa extensions","Extensions depend on the country, the visa type and when you apply.",[
("Is an extension possible?",P("Some countries allow extensions for visitors and others do not. Where they exist, they are usually limited and not guaranteed.")),
("When and how to apply",UL("Apply before your permitted stay ends, and earlier if the official guidance says it takes weeks.","Expect to show a reason, funds, accommodation and a valid passport.","Keep the receipt or confirmation, because it can matter if you are checked.")),
("Do not overstay",P("Staying past your date without permission can cause bans and fines. Read <a href='/guides/overstay-consequences/'>what overstaying can mean</a>."))]),
("plan-your-visa-timeline","How to plan your visa timeline","Work backwards from your departure date and add buffers.",[
("Work backwards",P("Start from the date you must have the visa. Subtract processing time, the wait for an appointment, and time for your passport to be returned if it is held.")),
("Add buffers",P("Processing times can change without notice, and peak seasons slow everything down. A buffer of several weeks is safer than a tight schedule.")),
("Book smart",P("Where you can, choose flexible or refundable tickets until the visa is granted. Check the official source for current timings."))])]
def TAPE(): return "".join(f"<span>{i+1} &middot; {e(N[p])}<b>{score(p)}</b></span>" for i,p in enumerate(RANK[:14]))
def GL(): return "".join(f"<a class='row' href='/guides/{s}/'><span>{t}</span><span class='mute'>{d}</span></a>" for s,t,d,_ in GUIDES()[:5])
def guides():
    G=GUIDES()
    for s,t,d,secs in G:
        ld='<script type="application/ld+json">'+json.dumps({"@context":"https://schema.org","@type":"Article","headline":t,"description":d,"dateModified":TODAY.isoformat(),"publisher":{"@type":"Organization","name":"Visa Radar"}})+'</script>'
        oth="".join(f"<a class='row' href='/guides/{x}/'><span>{y}</span></a>" for x,y,_,_ in G if x!=s)[:0]+"".join(f"<a class='row' href='/guides/{x}/'><span>{y}</span></a>" for x,y,_,_ in [g for g in G if g[0]!=s][:4])
        page(f"guides/{s}/",f"{t} | Visa Radar",d,f"<div class='prose'><h1>{t}</h1><p class='lede'>{d}</p>"+"".join(f"<h2>{h}</h2>{b}" for h,b in secs)+f"<p class='note'>General information only, last reviewed {TODAY.strftime('%d %B %Y')}. Rules change, so confirm with the official source. See our <a href='/disclaimer/'>disclaimer</a>.</p>{AD()}<h2>Keep reading</h2><div class='ledger'>{oth}</div></div>",ld)
    page("guides/","Travel Visa Guides | Visa Radar","In-depth guides to visa types, scams, the Schengen rule, applications and more.","<h1>Guides</h1><p class='lede'>Plain-language guides to visas, passports and entry rules.</p><div class='ledger'>"+"".join(f"<a class='row' href='/guides/{s}/'><span>{t}</span><span class='mute'>{d}</span></a>" for s,t,d,_ in G)+"</div><p><a href='/faq/'>Frequently asked questions</a> · <a href='/glossary/'>Glossary</a></p>")
    GL_=[("90/180 rule","Limit of 90 days in any rolling 180-day period for visa-exempt visitors to the Schengen Area."),("Airside transit","Changing planes without leaving the international area or passing border control."),("Biometrics","Fingerprints and a facial image collected at an embassy, visa centre or border."),("eTA","Electronic travel authorisation: an online pre-check linked to your passport, not a full visa."),("e-Visa","A visa applied for and approved online before travel."),("EES","The EU Entry/Exit System, a digital record of entries and exits for short-stay non-EU visitors."),("ETIAS","A planned EU travel authorisation for visa-exempt visitors. Not open for applications."),("Landside transit","Entering a country during a layover, which usually needs entry permission."),("Overstay","Staying beyond the permitted period, which can bring fines, bans and removal."),("Schengen Area","A group of European countries without internal border checks that share a common short-stay visa policy."),("Travel freedom score","On Visa Radar, the number of destinations a passport reaches visa-free, on arrival or with an eTA."),("Validity rule","A destination's minimum remaining passport validity, such as three or six months."),("Visa on arrival","A visa issued at the border or airport, usually for a fee."),("Visa-free","Entry without a prior visa application, for a set number of days.")]
    page("glossary/","Visa and Passport Glossary | Visa Radar","Definitions of common visa, passport and border terms.","<div class='prose'><h1>Glossary</h1><dl>"+"".join(f"<dt><strong>{t}</strong></dt><dd>{d}</dd>" for t,d in GL_)+"</dl></div>")
    FQ=[("Is Visa Radar an official government site?","No. Visa Radar is an independent information service and is not affiliated with any government, embassy or airline. Always confirm entry rules on the official source."),("How often is the data updated?",f"The site rebuilds from the latest open dataset every week. The current snapshot is dated {UPD}, and every page footer shows it."),("Why might my result differ from the embassy?","Our data is a community-maintained snapshot and rules can change at short notice. The embassy or official portal always takes priority."),("What is the difference between an eTA and a visa?","An eTA is a light online authorisation linked to your passport, while a visa is a fuller permission that usually needs more documents and time."),("Do I need a visa just to change planes?","Sometimes. It depends on your passport, the airport and whether you leave the transit area. Check the official site and your airline."),("How much passport validity do I need?","It depends on the destination. Many ask for three or six months beyond your stay. Use our passport validity checker once you know your destination's rule."),("Can I apply for ETIAS now?","No. ETIAS has not opened, so any site offering an application is not legitimate. See our ETIAS page for the latest status."),("How do I report a mistake?","Use the report link on any route page or email us with a link to the official source.")]
    ld='<script type="application/ld+json">'+json.dumps({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in FQ]})+'</script>'
    page("faq/","Visa and Passport FAQ | Visa Radar","Answers to common questions about visas, passports and how Visa Radar works.","<div class='prose'><h1>Frequently asked questions</h1>"+"".join(f"<h2>{q}</h2><p>{a}</p>" for q,a in FQ)+"</div>",ld)
def newspage():
    tg=[n for n,_ in TAGRX if any(n in ntags(i) for i in NEWS)]
    chips="<button type='button' class='chip' data-f='' aria-pressed='true'>All</button>"+"".join(f"<button type='button' class='chip' data-f='{n}' aria-pressed='false'>{n}</button>" for n in tg)
    body=f"<h1>Visa and travel entry news</h1><p class='lede'>Recent headlines on visas, border rules and entry requirements, collected from official and trade sources. Each item links to the original publisher.</p><p class='note'>Headlines are shown for information only. They are not official announcements and we do not verify them. Confirm any change on the official government site. See our <a href='/disclaimer/'>disclaimer</a>.</p>"
    body+=(f"<div class='chips' id='nf'>{chips}</div>{AD()}<div>{''.join(nitem(i) for i in NEWS)}</div><p class='mute'>Latest item: {fmtd(NEWS[0]['d'])}. The list refreshes automatically when the site rebuilds.</p>" if NEWS else "<p>No headlines yet. News refreshes automatically when the site rebuilds.</p>")
    page("news/","Visa and Travel Entry News | Visa Radar","Latest news on visa rules, e-visas, eTAs and border entry requirements.",body)
def editorial():
    page("editorial-policy/","Editorial Policy | Visa Radar","How Visa Radar gathers, checks and corrects its information.","<div class='prose'><h1>Editorial policy</h1><p class='lede'>How we decide what to publish and how we keep it accurate.</p><h2>Sources</h2><p>Entry-rule data comes from an open dataset whose snapshot date is shown on every page. Official government portals take priority over any secondary source, and we link to them wherever we have verified a link. News items are headlines from third-party publishers that link to the originals.</p><h2>Guides</h2><p>Guides cover rules that change rarely. We avoid publishing fees, processing times and other figures we cannot verify from an official source, and each guide shows a review date.</p><h2>Independence</h2><p>Advertising does not influence what we write or how passports and destinations are ranked. Rankings are calculated by the formula described on the rank page.</p><h2>Corrections</h2><p>If you find an error, use the report link on any route page or email us with a link to the official source. We correct confirmed mistakes promptly and update the review date.</p><h2>What we are not</h2><p>We are not a government agency, embassy or visa service. See our <a href='/disclaimer/'>disclaimer</a>.</p></div>")
def legal():
    ad=("<h2>Advertising</h2><p>This site uses Google AdSense. Google and its partners are third-party vendors that use cookies, including the DoubleClick cookie, to serve ads based on your visits to this and other sites. You can opt out of personalised advertising in <a href='https://adssettings.google.com'>Google Ads Settings</a> or at <a href='https://www.aboutads.info'>aboutads.info</a>. Where the law requires it (for example in the EEA, UK and Switzerland), we ask for your consent through a consent message before personalised ads are shown, and you can change your choice any time using the Ad and cookie settings link in the footer. Learn how Google uses data from sites that use its services at <a href='https://policies.google.com/technologies/partner-sites'>policies.google.com/technologies/partner-sites</a>. US visitors can limit ad data use through their state privacy choices in Google's ad settings.</p>" if ADS else "<h2>Advertising</h2><p>This site does not currently show advertising. If that changes, this policy will be updated first.</p>")
    P={"about":("About Visa Radar","<h1>About Visa Radar</h1><p class='lede'>Visa Radar helps travellers see, in seconds, whether their passport needs a visa for a destination.</p><h2>Where the data comes from</h2><p>Visa rules come from the open Passport Index dataset (MIT licence), snapshot dated "+UPD+". It covers "+str(len(R))+" passports. Country facts, weather and exchange rates are fetched live from REST Countries, Open-Meteo and ExchangeRate-API.</p><h2>How we keep it current</h2><p>The site rebuilds from the latest dataset every week. The snapshot date is shown in every page footer. Community datasets can lag behind government changes, so we ask you to verify with the official source.</p><h2>Corrections</h2><p>Found a mistake? Email <a href='mailto:"+MAIL+"'>"+MAIL+"</a> with the page address and an official source link.</p>"),
    "disclaimer":("Disclaimer","<h1>Disclaimer</h1><p class='lede'>Visa Radar is for general information only.</p><ul><li>We are not a government agency, embassy, consulate, airline or visa service, and we are not affiliated with any of them.</li><li>Entry rules change often and without notice. Our data is a community snapshot dated "+UPD+" and may be out of date or incomplete.</li><li>Nothing on this site is legal, immigration or travel advice. Border officers and airlines make the final decision on whether you may travel.</li><li>Always confirm requirements, fees, passport validity and health rules with the official government or embassy website before you book or travel.</li><li>Live information from third parties (weather, currency, country facts) is provided as is and may be delayed or unavailable.</li><li>News headlines and summaries come from third-party publishers and are shown for information only. We do not verify them, and they are not official announcements.</li><li>Links to other sites are for convenience. We do not control or endorse their content.</li><li>Visa Radar is not affiliated with Passport Index or any other data provider. Rankings and scores here are calculated by us from the dataset and can differ from other sites.</li><li>Advertising, if shown, is not an endorsement of any product or service.</li><li>To the fullest extent the law allows, we are not liable for any loss, denied boarding, fees or other harm resulting from use of this site.</li></ul>"),
    "terms":("Terms of use","<h1>Terms of use</h1><p>Last updated "+TODAY.strftime('%d %B %Y')+". By using Visa Radar you agree to these terms.</p><h2>Use of the site</h2><p>You may use the site for personal, lawful purposes. You may not scrape it in a way that harms its performance, attempt to break or overload it, or present its content as an official source.</p><h2>No advice, no guarantee</h2><p>Content is provided as is, without warranties of accuracy, completeness or fitness for a purpose. See the <a href='/disclaimer/'>disclaimer</a>. You are responsible for checking official sources.</p><h2>Intellectual property</h2><p>The design, text and code of this site belong to the operator. Visa data is derived from the Passport Index dataset under the MIT licence. Third-party names and data remain the property of their owners.</p><h2>Third-party services and links</h2><p>The site calls third-party services and links to other websites. Their terms and privacy policies apply to your use of them.</p><h2>Limitation of liability</h2><p>To the fullest extent permitted by law, the operator is not liable for indirect or consequential loss arising from use of the site.</p><h2>Advertising and external content</h2><p>The site may display third-party advertising and links to news and other external sites. We do not control or endorse them, and we are not responsible for their content, products or practices. Headlines and snippets in the news section belong to their publishers and link back to the originals.</p><h2>Changes and law</h2><p>We may update these terms; continued use means you accept the update. These terms are governed by the laws of the country where the operator is established.</p><p>Questions: <a href='mailto:"+MAIL+"'>"+MAIL+"</a></p>"),
    "privacy":("Privacy policy","<h1>Privacy policy</h1><p>Last updated "+TODAY.strftime('%d %B %Y')+". We keep data collection to a minimum.</p><h2>What we collect</h2><p>We do not offer accounts and do not ask you for personal data. Our hosting provider (Vercel) keeps standard server logs, such as IP address, browser and pages requested, for security and reliability.</p><h2>Stored in your browser</h2><p>The site saves your last passport and destination, your light or dark preference, and short-lived copies of API responses in your browser's local storage. This stays on your device and you can clear it at any time.</p><h2>Third-party services</h2><p>To show live details, your browser contacts REST Countries, Open-Meteo and ExchangeRate-API, which can see your IP address and browser details under their own policies. Fonts are loaded from Google Fonts.</p>"+ad+"<h2>Cookies and similar technologies</h2><p>The site itself sets no tracking cookies. It stores preferences and cached API responses in local storage. If advertising is enabled, Google and its partners may set cookies or use similar technologies to serve and measure ads, subject to your consent where required.</p><h2>Legal bases and retention</h2><p>Where the GDPR applies, we rely on legitimate interests to operate and secure the site and on your consent for personalised advertising cookies. Server logs are kept by our host for a limited period. We do not keep personal data of our own.</p><h2>International transfers</h2><p>Our host and third-party services may process data outside your country, under their own safeguards.</p><h2>Your rights</h2><p>Depending on where you live (for example under the GDPR, UK GDPR or CCPA), you may have rights to access, correct or delete personal data, to withdraw consent, to object to its use or to complain to a regulator. Contact us and we will respond.</p><h2>Children</h2><p>This site is not directed at children under 13.</p><h2>Contact</h2><p><a href='mailto:"+MAIL+"'>"+MAIL+"</a></p>"),
    "contact":("Contact","<h1>Contact</h1><p class='lede'>Email <a href='mailto:"+MAIL+"'>"+MAIL+"</a>.</p><p>To report a data error, include the page address and a link to the official source. We cannot give individual visa advice or process visa applications.</p>")}
    for k,(t,b) in P.items(): page(k+"/",t+" | Visa Radar",t+" for Visa Radar.",f"<div class='prose'>{b}</div>")
    if ADS: open(f"{OUT}/ads.txt","w").write(f"google.com, {ADS.replace('ca-','')}, DIRECT, f08c47fec0942fa0\n")
def build():
    shutil.rmtree(OUT,ignore_errors=True); os.makedirs(f"{OUT}/assets"); os.makedirs(f"{OUT}/data")
    for f in ("style.css","app.js"): shutil.copy(f"src/{f}",f"{OUT}/assets/{f}")
    json.dump({"u":UPD,"n":N,"r":R},open(f"{OUT}/data/rules.json","w"),separators=(",",":"))
    top="".join(f'<a class="row" href="/passport/{p.lower()}/"><span class="rank">{i+1}</span><span>{e(N[p])}</span><span class="mute">{score(p)} destinations</span></a>' for i,p in enumerate(RANK[:10]))
    pop="".join(f'<a class="row" href="/{sl(p,d)}"><span>{e(N[p])} → {e(N[d])}</span><span class="mute">{lab(R[p][d])}</span></a>' for p,d in [("US","JP"),("GB","US"),("IN","GB"),("AE","FR"),("PK","TR"),("EG","DE"),("PH","JP"),("SA","GB")] if (p,d) in CORR)
    page("","Visa Radar: visa rules for every passport",f"Check visa requirements for {len(R)} passports and {len(N)} destinations, with live weather, currency and country details.",f'''<section class="hero"><canvas id="fx" aria-hidden="true"></canvas><div class="glow"></div>{RADAR}<div><h1>Where can your passport take you?</h1><p class="lede">Pick a passport and a destination. See the entry rule, how long you can stay and what to do next.</p><div class="stats"><div><b data-count="{len(R)}">{len(R)}</b><span>passports</span></div><div><b data-count="{len(N)}">{len(N)}</b><span>destinations</span></div><div><b data-count="{sum(len(d) for d in R.values())}">{sum(len(d) for d in R.values()):,}</b><span>routes checked</span></div></div></div><form class="ticket" id="lookup" onsubmit="return false"><label>Passport<select id="from"></select></label><label>Destination<select id="to"></select></label><div id="stamp" aria-live="polite"><noscript>Turn on JavaScript to use the lookup, or browse the passport pages below.</noscript></div><p class="fine">Confirm on the official government site before you travel. <a href="/disclaimer/">Read the disclaimer</a>.</p></form></section><div class="tape" aria-hidden="true"><div>{TAPE()}{TAPE()}</div></div>
<section><h2>Explore</h2><div class="ledger"><a class="row" href="/rank/"><span>Global passport rank</span><span class="mute">All {len(R)} passports by travel freedom</span></a><a class="row" href="/rank/welcoming/"><span>Welcoming destinations</span><span class="mute">Which countries let the most passports in</span></a><a class="row" href="/compare/"><span>Compare passports</span><span class="mute">Up to four side by side</span></a><a class="row" href="/compare/destinations/"><span>Compare destinations</span><span class="mute">Entry rules and openness</span></a><a class="row" href="/map/"><span>Visa map</span><span class="mute">Any passport, coloured by rule</span></a><a class="row" href="/charts/"><span>Charts</span><span class="mute">Rankings and the global mix</span></a><a class="row" href="/tools/"><span>All tools</span><span class="mute">Trip checker, dual passport, compare, map, 90/180</span></a><a class="row" href="/changes/"><span>What changed</span><span class="mute">Rule changes since {OLDP}</span></a><a class="row" href="/eu/"><span>EU entry: EES, ETIAS, 90/180 calculator</span><span class="mute">Status and tools</span></a></div></section>{NH()}<section><h2>Guides</h2><div class="ledger">{GL()}</div><p><a href="/guides/">All guides</a> · <a href="/faq/">FAQ</a> · <a href="/glossary/">Glossary</a></p></section><section><h2>Strongest passports</h2><p class="mute">Ranked by destinations reachable without a visa, on arrival or with an electronic authorisation.</p><div class="ledger">{top}</div><p><a href="/passport/">All {len(R)} passports</a></p></section>
<section><h2>Popular routes</h2><div class="ledger">{pop}</div></section><section><h2>How this site works</h2><p class="lede">Visa rules come from the open Passport Index dataset, dated {UPD}. Country details, weather and exchange rates are fetched live. Every page links back to the official-source reminder because rules change quickly. Read <a href="/about/">about us</a>, the <a href="/disclaimer/">disclaimer</a> and <a href="/terms/">terms of use</a>.</p></section>''')
    index_page("passport/","Visa rules by passport",R,"passport/"); index_page("country/","Destination guides",N,"country/")
    for p in R:
        c=CNT[p]; body=f'<h1>{e(N[p])} passport</h1><p class="lede">Ranked {POS[p]} of {len(R)}. Visa-free to {c["vf"]} destinations, visa on arrival in {c["voa"]}, electronic authorisation for {c["eta"]}, e-visa for {c["ev"]}, and a visa needed for {c["vr"]+c["na"]}.</p>'
        for k in K:
            ds=sorted([d for d,v in R[p].items() if kind(v)==k],key=lambda d:N[d])
            if ds: body+=f'<section><h2>{INFO[k][0]} <span class="mute">{len(ds)}</span></h2><div class="chips">{"".join(chip(p,d) for d in ds)}</div></section>'
        body+=csec(CHP.get(p,[]),"p")
        page(f"passport/{p.lower()}/",f"{N[p]} Passport Visa Requirements | Visa Radar",f"Where {N[p]} passport holders can travel: {c['vf']} visa-free, {c['voa']} on arrival, {c['eta']} eTA, {c['ev']} e-visa destinations.",body)
    for d in N:
        inb={p:R[p][d] for p in R if d in R[p]}; cc={k:sum(1 for v in inb.values() if kind(v)==k) for k in K}
        body=f'<h1>Travel to {e(N[d])}</h1><p class="lede">Visa-free for {cc["vf"]} passports, on arrival for {cc["voa"]}, electronic authorisation for {cc["eta"]}, e-visa for {cc["ev"]}, and a visa required for {cc["vr"]+cc["na"]}.</p>'+LIVE(d)
        for k in K:
            ps=sorted([p for p,v in inb.items() if kind(v)==k],key=lambda p:N[p])
            if ps: body+=f'<details{" open" if k=="vf" else ""}><summary>{INFO[k][0]} ({len(ps)} passports)</summary><div class="chips">{"".join(f"<a class=chip href=/passport/{p.lower()}/>{e(N[p])}</a>" for p in ps)}</div></details>'
        body+=nsec(d)+srcs(d)+csec(CHD2.get(d,[]),"d")
        page(f"country/{d.lower()}/",f"Travel to {N[d]}: Entry Rules & Live Details | Visa Radar",f"Who needs a visa for {N[d]}, plus live weather, currency and country facts.",body)
    for p,d in sorted(CORR):
        v=R[p][d]; k=kind(v); oth=[x for x in DD if (p,x) in CORR and x!=d][:8]
        body=f'<h1>{e(N[p])} passport to {e(N[d])}</h1>{stamp(v)}<p class="lede">{INFO[k][1]}</p>{chnote(p,d)}<h2>What to do</h2><ol>{"".join(f"<li>{s}</li>" for s in INFO[k][2])}</ol><p class="note">Confirm this on the official {e(N[d])} government or embassy site. Dataset snapshot dated {UPD}.</p>'+srcs(d)+report(p,d)+LIVE(d)+f'<h2>More from {e(N[p])}</h2><div class="chips">{"".join(chip(p,x) for x in oth)}</div><p><a href="/passport/{p.lower()}/">All {e(N[p])} passport rules</a> · <a href="/country/{d.lower()}/">Everyone entering {e(N[d])}</a></p>'
        q=f"Do {N[p]} citizens need a visa for {N[d]}?"; ld=f'<script type="application/ld+json">{json.dumps({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":lab(v)+". "+INFO[k][1]}}]})}</script>'
        page(sl(p,d),f"{N[p]} to {N[d]} Visa: {INFO[k][0]} | Visa Radar",f"{q} {lab(v)}. Steps, stay allowed and live destination details.",body,ld)
    features()
    changes()
    eu()
    tools()
    validity()
    guides()
    newspage()
    editorial()
    legal()
    open(f"{OUT}/sitemap.xml","w").write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+"".join(f"<url><loc>{u}</loc><lastmod>{TODAY}</lastmod></url>" for u in PAGES)+"</urlset>")
    open(f"{OUT}/robots.txt","w").write(f"User-agent: *\nAllow: /\nSitemap: {SITE}/sitemap.xml\n"); print(len(PAGES),"pages; data",UPD)
build()
